### ISSUE TITLE
Tùy chỉnh sự kiện sever. Không hoạt động 

### ISSUE THREAD

**Issue by xuyen18012000** [KhanhNguyen9872/Ninja_Server_Termux#10]
Sever: FullNhiemVu-VIP-2022  có chỗ  cài đặt chỉnh sự kiện sever để chỉnh thì chỉnh được nhưng cài. 000. Update Goosho [Vật phẩm sự kiện] thì nó không cập nhập vật phẩm cho sự kiện vừa chỉnh dẫn đến không thể làm được vật phẩm sk.. mong admin giải quyết thắc mắc giúp mình. Thank you

**Comment by KhanhNguyen9872** [comment]
> Sever: FullNhiemVu-VIP-2022 có chỗ cài đặt chỉnh sự kiện sever để chỉnh thì chỉnh được nhưng cài. 000. Update Goosho [Vật phẩm sự kiện] thì nó không cập nhập vật phẩm cho sự kiện vừa chỉnh dẫn đến không thể làm được vật phẩm sk.. mong admin giải quyết thắc mắc giúp mình. Thank you

cảm ơn bạn đã report, mình xin trả lời như sau:
1. phần thay đổi sự kiện nó hoạt động, nhưng sau khi đổi bạn nhớ phải khởi động lại server ninja bằng cách sang tab lệnh ninja, nhấn Ctrl + C và gõ lại ninja để mở lại server
2. phần update Goosho chỉ update vật phẩm sự kiện hè, còn các sự kiện khác thì bạn đánh quái là đủ đồ làm sk bên Cô Tiên rồi nhé

**Comment by xuyen18012000** [comment]
Có làm được vật phẩm sự kiện 
Ví dụ: sự kiện tết .làm bánh 
Nhưng lúc sử dụng bánh lại ghi là Vật phẩm không thể sử dụng trực tiếp admin ạ 
Sk hè làm ra diều thì vẫn dùng bth còn các sk khác thì nó ghi thế

**Comment by KhanhNguyen9872** [comment]
> Có làm được vật phẩm sự kiện Ví dụ: sự kiện tết .làm bánh Nhưng lúc sử dụng bánh lại ghi là Vật phẩm không thể sử dụng trực tiếp admin ạ Sk hè làm ra diều thì vẫn dùng bth còn các sk khác thì nó ghi thế

-> theo mình biết thì khi làm bánh xong nó sẽ dùng đc mà nhỉ? bạn có biết sự kiện đó liệu có cần thêm vật phẩm gì k ạ? để mình add vào

**Comment by xuyen18012000** [comment]
Đủ nguyên liệu admin ạ vẫn làm được nhưng lúc dùng lại k được ý

**Comment by KhanhNguyen9872** [comment]
> Đủ nguyên liệu admin ạ vẫn làm được nhưng lúc dùng lại k được ý

cái đó thì e cũng k rõ nữa ạ hihi, tại source này của ng khác ạ chứ e k phải người viết source nso
nếu bạn k còn câu hỏi nào, e xin phép đóng issue ạ

**Comment by anhduc2003** [comment]
Ad thêm source này vào termux nha

https://mega.nz/file/ySRmRaRY#RMyC7eJel3pFSZ3hRV-Dz3ACoOQ82x2QRiLpOPzNdSc

pass : tambietnsolau

Vào 16:22, CN, 2 thg 10, 2022 Nguyễn Văn Khánh ***@***.***>
đã viết:

**Comment by xuyen18012000** [comment]
> 

Gì đây
