### ISSUE TITLE
Túi kim lượg hoiuc_2_2022

### ISSUE THREAD

**Issue by haizippro23** [KhanhNguyen9872/Ninja_Server_Termux#12]
Ad bỏ túi kim lượng ra khỏi của hàng của NPC kiriko đc không chứ bug quá
Vào game nhận quà tân thủ 10k lượng up lên lv50 dùng 100 lượng mua cái túi đó mở ra 50k 60k lượng rồi

**Comment by KhanhNguyen9872** [comment]
> Ad bỏ túi kim lượng ra khỏi của hàng của NPC kiriko đc không chứ bug quá Vào game nhận quà tân thủ 10k lượng up lên lv50 dùng 100 lượng mua cái túi đó mở ra 50k 60k lượng rồi

cảm ơn bạn đã report!
phiên bản 104 sẽ đc update vào trưa nay! bạn update lên sau đó cài đặt lại database (xóa toàn bộ tài khoản và chơi lại nhé)
