### ISSUE TITLE
Dung lượng cài đặt

### ISSUE THREAD

**Issue by Layiua** [KhanhNguyen9872/Ninja_Server_Termux#13]
Bây giờ để cài đặt thì cần khoảng bao nhiêu dung lượng vậy anh?

**Comment by KhanhNguyen9872** [comment]
> Bây giờ để cài đặt thì cần khoảng bao nhiêu dung lượng vậy anh?

trống tầm 3gb bạn nhé, còn nếu bạn cài thêm 1 số tùy chọn các trong menu thì cao hơn nha, 3gb là chứa file data cài và cài vào, nên sau khi xong chắc cũng cỡ  2gb thôi bạn
