### ISSUE TITLE
Giải đáp thắc mắc

### ISSUE THREAD

**Issue by xuyen18012000** [KhanhNguyen9872/Ninja_Server_Termux#17]
Admin cho mình hỏi 
sv FullNhiemVu-VIP-2022 [MoonSmile] 
Có thể chỉnh được chỉ số vật phẩm không. Tại mình thấy có rất nhiều vật phẩm vd như trang bị 2 thì k có chỉ số 😕 
Nếu có Thì ad có thể cho vào menu termux đc k ạ
Thank.

**Comment by KhanhNguyen9872** [comment]
> Admin cho mình hỏi sv FullNhiemVu-VIP-2022 [MoonSmile] Có thể chỉnh được chỉ số vật phẩm không. Tại mình thấy có rất nhiều vật phẩm vd như trang bị 2 thì k có chỉ số 😕 Nếu có Thì ad có thể cho vào menu termux đc k ạ Thank.

bạn có thể dùng phpmyadmin nhé
http://127.0.0.1:8080/phpmyadmin
hoặc vào menu -> 7, có mục chỉnh shop, vật phẩm trong kho đồ nha

**Comment by xuyen18012000** [comment]
Admin cho mình xin tên ứng dụng chỉnh phpmyadmin trên điện thoại được k ạ😕

**Comment by xuyen18012000** [comment]
> 

Mình vào Http://127.0.0.1:8080/phpmyadmin k truy cập vào đc admin ạ

**Comment by KhanhNguyen9872** [comment]
> > 
> 
> Mình vào [Http://127.0.0.1:8080/phpmyadmin](Http://127.0.0.1:8080/phpmyadmin) k truy cập vào đc admin ạ

bạn phải chạy tamp cơ, chứ không không lấy đâu cái cho b vào:)))
