### ISSUE TITLE
Lỗi

### ISSUE THREAD

**Issue by ttnb2528** [KhanhNguyen9872/Ninja_Server_Termux#26]
Mình ko thể cài file game, bảo file ko còn trên server :((

**Comment by KhanhNguyen9872** [comment]
> Mình ko thể cài file game, bảo file ko còn trên server :((

b cấp quyền bộ nhớ cho termux nhé

**Comment by ttnb2528** [comment]
Ohhh nice, anh có dự định thêm những bản mod khác nữa ko ạ
