### ISSUE TITLE
lỗi chạy lệnh ninja

### ISSUE THREAD

**Issue by retnetfihs** [KhanhNguyen9872/Ninja_Server_Termux#4]
![image](https://user-images.githubusercontent.com/106880630/172018728-49a04864-f0f1-4133-bbbf-9208cd6d94c9.png)

**Comment by ngoc65611686** [comment]
mình cũng bị lỗi, chắc tại lúc tối ổng sửa cái gì á

**Comment by KhanhNguyen9872** [comment]
> ![image](https://user-images.githubusercontent.com/106880630/172018728-49a04864-f0f1-4133-bbbf-9208cd6d94c9.png)

Đã fix cách đây vài ngày rồi nha:D
