### ISSUE TITLE
Lỗi Sever

### ISSUE THREAD

**Issue by thucvan96643** [KhanhNguyen9872/Ninja_Server_Termux#5]
Em Chọn New Session Xong Gõ Ninja Nó Ra Lỗi Sever Vui Lòng Cài Đặt Lại Là Sao Anh.
![Screenshot_2022-06-16-08-43-29-11](https://user-images.githubusercontent.com/107595048/173973669-c34548a8-6544-44c5-aaf8-0bae90d140fe.jpg)

**Comment by thucvan96643** [comment]
Giúp e vs ạ

**Comment by duongvps** [comment]
Thử cài đặt lại đi bạn

**Comment by KhanhNguyen9872** [comment]
> Em Chọn New Session Xong Gõ Ninja Nó Ra Lỗi Sever Vui Lòng Cài Đặt Lại Là Sao Anh. ![Screenshot_2022-06-16-08-43-29-11](https://user-images.githubusercontent.com/107595048/173973669-c34548a8-6544-44c5-aaf8-0bae90d140fe.jpg)

cài hoàn tất là đc nha
