### ISSUE TITLE
MySQL is not running

### ISSUE THREAD

**Issue by Kaydee2109** [KhanhNguyen9872/Ninja_Server_Termux#6]
![Screenshot_2022-08-04-06-30-28-63_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/110574091/182730545-9db0906f-d0c8-47bd-97c7-d69aa5585fab.jpg)

**Comment by KhanhNguyen9872** [comment]
> ![Screenshot_2022-08-04-06-30-28-63_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/110574091/182730545-9db0906f-d0c8-47bd-97c7-d69aa5585fab.jpg)

try reboot your device and run tamp -start again!
if not work, try reinstall termux <3
thanks

**Comment by KhanhNguyen9872** [comment]
> ![Screenshot_2022-08-04-06-30-28-63_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/110574091/182730545-9db0906f-d0c8-47bd-97c7-d69aa5585fab.jpg)

don't try to force stop while tamp is running, because it can cause unexpected errors, you can use the Exit Termux feature in the menu
