### ISSUE TITLE
Lỗi không đăng nhập được

### ISSUE THREAD

**Issue by xuyen18012000** [KhanhNguyen9872/Ninja_Server_Termux#9]
Chạy máy chủ online đăng nhập lúc vừa mở sever bằng lệnh "ninja" thì vào được game. Nhưng 1 lúc thoát ra vào lại thì không vào được nữa trên termux hiện dòng chữ
"Close Send thread
Close Send thread
Close Send thread
Close Send thread
Close receive thread
Close Send thread
Close Send thread
Close receive thread
Close receive thread
Close receive thread
Close receive thread
Close receive thread
Close receive thread
Close Send thread" 
Mong admin giúp đỡ

**Comment by KhanhNguyen9872** [comment]
bạn đang

> Chạy máy chủ online đăng nhập lúc vừa mở sever bằng lệnh "ninja" thì vào được game. Nhưng 1 lúc thoát ra vào lại thì không vào được nữa trên termux hiện dòng chữ "Close Send thread Close Send thread Close Send thread Close Send thread Close receive thread Close Send thread Close Send thread Close receive thread Close receive thread Close receive thread Close receive thread Close receive thread Close receive thread Close Send thread" Mong admin giúp đỡ

bạn đang chơi Online hay Offline?
nếu bạn chơi Online, có vẻ như server bạn đang bị 1 ai đó chạy DDOS
hoặc nếu bạn chơi Offline, hãy thử bấm Ctrl + C ở tab lệnh ninja, và sau đó gõ lại ninja để chạy lại server nhé!

**Comment by xuyen18012000** [comment]
Oki cảm ơn ad

**Comment by KhanhNguyen9872** [comment]
> Oki cảm ơn ad

nếu bạn k còn thắc mắc gì nữa, mình xin đóng issue ạ, nếu bạn có cứ tạo 1 issue khác nhé! chúc bạn ngủ ngon
